"""Translate argparse module but in a very hacky way."""

_tr("usage: ")
#_tr(".__call__() not defined")
#_tr("unknown parser %(parser_name)r (choices: %(choices)s)")
#_tr("argument \"-\" with mode %r")
#_tr("can't open '%(filename)s': %(error)s")
#_tr("cannot merge actions - two groups are named %r")
#_tr("'required' is an invalid argument for positionals")
#_tr("invalid option string %(option)r: must start with a character ")
#_tr("%(prefix_chars)r")
#_tr("dest= is required for options like %r")
#_tr("invalid conflict_resolution value: %r")
#_tr("conflicting option string: %s")
#_tr("conflicting option strings: %s")
#_tr("mutually exclusive arguments must be optional")
#_tr("positional arguments")
_tr("options")
_tr("show this help message and exit")
#_tr("cannot have multiple subparser arguments")
_tr("unrecognized arguments: %s")
#_tr("not allowed with argument %s")
#_tr("ignored explicit argument %r")
_tr("the following arguments are required: %s")
#_tr("one of the arguments %s is required")
_tr("expected one argument")
#_tr("expected at most one argument")
#_tr("expected at least one argument")
#_tr("expected %s argument")
#_tr("expected %s arguments")
#_tr("ambiguous option: %(option)s could match %(matches)s")
#_tr("unexpected option string: %s")
#_tr("%r is not callable")
#_tr("invalid %(type)s value: %(value)r")
#_tr("invalid choice: %(value)r (choose from %(choices)s)")
_tr("%(prog)s: error: %(message)s\n")
